name: Actions Workflow
on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List File
        run: |
          pwd
          ls 
          ls -a
      - name: Chekout
        uses: actions/checkout@v1
      - name: List Files after checkout
        run: |
          pwd
          ls 
          ls -a
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Mukesh
      - name: Log Greeting time
        run: echo "${{ steps.greet.outputs.time }}"
      - name: Githu Environment Variables
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          ech0 $GITHUB_WORKSPACE
          # echo "${{ github.token }}"
          # git clone git@github:$GITHUB_REPOSITORY
